name: poker
favicon: null
layout_spectrum: 0.39884861931204796
typography_spectrum: 0.05742374830879271
title: Poker On Air
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3711240428965539
  lightness: 0.11123387864790857
  saturation: 0.4223855247255415
  rhythmicContrast: 0.5156855103559792
purpose: []
